/**
 * Dynamic URL & Security Salts Config Patcher (config_patcher.mjs)
 * Module: scripts/config_patcher.mjs
 *
 * Responsibilities:
 * 1. Injects dynamic URL detection snippet into wp-config.php and wp-config-sample.php (idempotent).
 * 2. Generates cryptographic 64-char security salts for all 8 standard WordPress keys.
 * 3. Standardizes .htaccess rewrite rules (replaces hardcoded subfolder paths, creates if missing).
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const SALT_KEYS = [
  'AUTH_KEY',
  'SECURE_AUTH_KEY',
  'LOGGED_IN_KEY',
  'NONCE_KEY',
  'AUTH_SALT',
  'SECURE_AUTH_SALT',
  'LOGGED_IN_SALT',
  'NONCE_SALT',
];

const DEFAULT_SNIPPET_PATH = path.resolve(__dirname, '../templates/dynamic-config-snippet.php');
const DEFAULT_HTACCESS_PATH = path.resolve(__dirname, '../templates/htaccess-standard.txt');

/**
 * Returns the Dynamic URL snippet, loading from template file or fallback.
 */
export function getDynamicSnippet() {
  if (fs.existsSync(DEFAULT_SNIPPET_PATH)) {
    let raw = fs.readFileSync(DEFAULT_SNIPPET_PATH, 'utf8');
    // Strip leading <?php tag and whitespace so it can be safely injected inside wp-config.php
    raw = raw.replace(/^<\?php\s*/i, '').trim();
    return raw;
  }

  return `/**
 * Dynamic URL Detection for WordPress wp-config.php
 * Generated by wordpress-packaging-handover skill
 */
if (!defined('WP_HOME') || !defined('WP_SITEURL')) {
    if (php_sapi_name() !== 'cli' && isset($_SERVER['HTTP_HOST'])) {
        $is_https = (!empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off')
            || (isset($_SERVER['SERVER_PORT']) && (int)$_SERVER['SERVER_PORT'] === 443)
            || (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https')
            || (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && strtolower($_SERVER['HTTP_X_FORWARDED_SSL']) === 'on');

        $protocol = $is_https ? 'https://' : 'http://';
        $host = $_SERVER['HTTP_HOST'];

        $raw_script = isset($_SERVER['SCRIPT_NAME']) ? $_SERVER['SCRIPT_NAME'] : '/index.php';
        $script_dir = str_replace('\\\\', '/', dirname($raw_script));
        $clean_dir = preg_replace('#/(wp-admin|wp-content|wp-includes).*$#', '', $script_dir);
        $clean_dir = trim($clean_dir, '/');
        $site_path = ($clean_dir === '' || $clean_dir === '.') ? '' : '/' . $clean_dir;

        $dynamic_site_url = rtrim($protocol . $host . $site_path, '/');

        if (!defined('WP_HOME')) {
            define('WP_HOME', $dynamic_site_url);
        }
        if (!defined('WP_SITEURL')) {
            define('WP_SITEURL', $dynamic_site_url);
        }
    }
}`;
}

/**
 * Returns standard WordPress .htaccess template content.
 */
export function getStandardHtaccess() {
  if (fs.existsSync(DEFAULT_HTACCESS_PATH)) {
    return fs.readFileSync(DEFAULT_HTACCESS_PATH, 'utf8');
  }

  return `# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L]
</IfModule>
# END WordPress
`;
}

/**
 * Checks whether content already contains dynamic URL detection logic.
 */
export function hasDynamicUrl(content) {
  if (!content) return false;

  const hasHttpHost = /_SERVER\s*\[\s*['"]HTTP_HOST['"]\s*\]/.test(content);
  const hasWpHomeOrSiteUrl = /define\s*\(\s*['"](WP_HOME|WP_SITEURL)['"]/.test(content) ||
                             /['"](WP_HOME|WP_SITEURL)['"]/.test(content);

  if (hasHttpHost && hasWpHomeOrSiteUrl) {
    return true;
  }

  if (content.includes('Dynamic URL Detection for WordPress')) {
    return true;
  }

  return false;
}

/**
 * Injects dynamic URL snippet into PHP config content.
 * Prioritizes right after DB_COLLATE definition.
 */
export function injectDynamicUrl(content, snippet) {
  if (hasDynamicUrl(content)) {
    return { content, injected: false };
  }

  const formattedSnippet = `\n/* ==========================================================================\n * [TỰ ĐỘNG NHẬN DIỆN URL THEO THƯ MỤC VÀ TÊN MIỀN HIỆN TẠI]\n * Cho phép tạo thư mục mới bất kỳ trong htdocs hoặc đổi domain/port mà không bị lỗi\n * ========================================================================== */\n${snippet}\n`;

  // 1. After DB_COLLATE definition
  const dbCollateMatch = content.match(/(define\s*\(\s*['"]DB_COLLATE['"]\s*,[^;]*\);\s*\r?\n)/i);
  if (dbCollateMatch) {
    const idx = dbCollateMatch.index + dbCollateMatch[0].length;
    const newContent = content.slice(0, idx) + formattedSnippet + content.slice(idx);
    return { content: newContent, injected: true };
  }

  // 2. Before Authentication keys & salts block
  const saltsMatch = content.match(/(\/\*\*#@\+\s*\r?\n\s*\*\s*Authentication unique keys)/i);
  if (saltsMatch) {
    const idx = saltsMatch.index;
    const newContent = content.slice(0, idx) + formattedSnippet + '\n' + content.slice(idx);
    return { content: newContent, injected: true };
  }

  // 3. After any DB_* constant
  const lastDbMatch = content.match(/(define\s*\(\s*['"]DB_[A-Z_]+['"]\s*,[^;]*\);\s*\r?\n)(?!\s*define\s*\(\s*['"]DB_)/i);
  if (lastDbMatch) {
    const idx = lastDbMatch.index + lastDbMatch[0].length;
    const newContent = content.slice(0, idx) + formattedSnippet + content.slice(idx);
    return { content: newContent, injected: true };
  }

  // 4. Before stop editing line
  const stopMatch = content.match(/(\/\*\s*That's all,\s*stop editing!)/i);
  if (stopMatch) {
    const idx = stopMatch.index;
    const newContent = content.slice(0, idx) + formattedSnippet + '\n' + content.slice(idx);
    return { content: newContent, injected: true };
  }

  // 5. Fallback: append
  return { content: content + '\n' + formattedSnippet, injected: true };
}

/**
 * Generates a cryptographically secure 64-character salt string.
 * Using crypto.randomBytes(48).toString('base64') produces exactly 64 base64 chars without quotes or backslashes.
 */
export function generateSalt(length = 64) {
  if (length === 64) {
    return crypto.randomBytes(48).toString('base64');
  }

  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!#$%&*+-=?@^_~';
  const bytes = crypto.randomBytes(length);
  let res = '';
  for (let i = 0; i < length; i++) {
    res += chars[bytes[i] % chars.length];
  }
  return res;
}

/**
 * Regenerates the 8 standard WordPress keys/salts in config content.
 */
export function regenerateSaltsInContent(content) {
  let updated = content;
  let anyReplaced = false;

  for (const key of SALT_KEYS) {
    const newSalt = generateSalt(64);
    const regex = new RegExp(`(define\\s*\\(\\s*['"]${key}['"]\\s*,\\s*)(?:'[^']*'|"[^"]*")(\\s*\\);)`, 'g');
    if (regex.test(updated)) {
      updated = updated.replace(regex, `$1'${newSalt}'$2`);
      anyReplaced = true;
    }
  }

  return {
    content: updated,
    regenerated: anyReplaced,
  };
}

/**
 * Standardizes .htaccess in projectPath:
 * - Creates standard .htaccess if missing.
 * - Replaces hardcoded subfolder rewrite rules within the WordPress block.
 */
export function standardizeHtaccessFile(projectPath) {
  const htaccessPath = path.join(projectPath, '.htaccess');
  const standardTemplate = getStandardHtaccess().trim();

  if (!fs.existsSync(htaccessPath)) {
    fs.writeFileSync(htaccessPath, standardTemplate + '\n', 'utf8');
    return true;
  }

  const original = fs.readFileSync(htaccessPath, 'utf8');
  let updated = original;

  if (/# BEGIN WordPress[\s\S]*?# END WordPress/.test(updated)) {
    updated = updated.replace(/# BEGIN WordPress[\s\S]*?# END WordPress/, standardTemplate);
  } else {
    const beforeRewrite = updated;
    updated = updated.replace(/RewriteBase\s+\/[^\s\/]+\//g, 'RewriteBase /');
    updated = updated.replace(/RewriteRule\s+\.\s+\/[^\s\/]+\/index\.php/g, 'RewriteRule . index.php');
    if (updated === beforeRewrite && !updated.includes('RewriteEngine On')) {
      updated = updated.trim() + '\n\n' + standardTemplate + '\n';
    }
  }

  const normalize = (s) => s.replace(/\r\n/g, '\n').trim();
  if (normalize(updated) !== normalize(original)) {
    fs.writeFileSync(htaccessPath, updated.trim() + '\n', 'utf8');
    return true;
  }

  return false;
}

/**
 * Main patchConfig interface
 *
 * @param {string} projectPath Path to WordPress root directory
 * @param {object} options Options object:
 *   - regenerateSalts {boolean}: Regenerate 8 cryptographic salts (default: false)
 *   - standardizeHtaccess {boolean}: Standardize .htaccess rewrite rules (default: true)
 * @returns {Promise<{ patchedConfig: boolean, patchedSample: boolean, regeneratedSalts: boolean, updatedHtaccess: boolean }>}
 */
export async function patchConfig(projectPath, options = {}) {
  if (!projectPath || typeof projectPath !== 'string') {
    throw new Error('projectPath is required and must be a string');
  }

  const resolvedPath = path.resolve(projectPath);
  if (!fs.existsSync(resolvedPath)) {
    throw new Error(`projectPath does not exist: ${resolvedPath}`);
  }

  const {
    regenerateSalts = false,
    standardizeHtaccess = true,
  } = options;

  let patchedConfig = false;
  let patchedSample = false;
  let regeneratedSalts = false;
  let updatedHtaccess = false;

  const configPath = path.join(resolvedPath, 'wp-config.php');
  const samplePath = path.join(resolvedPath, 'wp-config-sample.php');
  const snippet = getDynamicSnippet();

  // 1. Patch wp-config.php
  if (fs.existsSync(configPath)) {
    let content = fs.readFileSync(configPath, 'utf8');
    let modified = false;

    if (!hasDynamicUrl(content)) {
      const injectRes = injectDynamicUrl(content, snippet);
      if (injectRes.injected) {
        content = injectRes.content;
        patchedConfig = true;
        modified = true;
      }
    }

    if (regenerateSalts) {
      const saltRes = regenerateSaltsInContent(content);
      if (saltRes.regenerated) {
        content = saltRes.content;
        regeneratedSalts = true;
        modified = true;
      }
    }

    if (modified) {
      fs.writeFileSync(configPath, content, 'utf8');
    }
  }

  // 2. Patch wp-config-sample.php
  if (fs.existsSync(samplePath)) {
    let sampleContent = fs.readFileSync(samplePath, 'utf8');
    let sampleModified = false;

    if (!hasDynamicUrl(sampleContent)) {
      const injectSampleRes = injectDynamicUrl(sampleContent, snippet);
      if (injectSampleRes.injected) {
        sampleContent = injectSampleRes.content;
        patchedSample = true;
        sampleModified = true;
      }
    }

    if (sampleModified) {
      fs.writeFileSync(samplePath, sampleContent, 'utf8');
    }
  }

  // 3. Standardize .htaccess
  if (standardizeHtaccess) {
    updatedHtaccess = standardizeHtaccessFile(resolvedPath);
  }

  return {
    patchedConfig,
    patchedSample,
    regeneratedSalts,
    updatedHtaccess,
  };
}

// CLI execution support
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const targetDir = process.argv[2] || process.cwd();
  const doRegen = process.argv.includes('--regenerate-salts');

  console.log(`Patching WordPress configuration in: ${targetDir}`);
  patchConfig(targetDir, { regenerateSalts: doRegen })
    .then((result) => {
      console.log('Patch complete:', result);
    })
    .catch((err) => {
      console.error('Error patching config:', err.message);
      process.exit(1);
    });
}
