<?php
/**
 * Dynamic URL Detection for WordPress wp-config.php
 * 
 * Tu dong nhan dien giao thuc (HTTP/HTTPS), Host, Port va thu muc con (subfolder)
 * giup website hoat dong ngay lap tuc tren moi moi truong (Localhost XAMPP, Laragon, Staging, Live)
 * ma khong can sua thu cong wp-config.php hoac bi loi chuyen huong khi doi thu muc/port.
 *
 * Generated by wordpress-packaging-handover skill
 */

if (!defined('WP_HOME') || !defined('WP_SITEURL')) {
    // Chi ap dung khi truy cap qua Web Server, khong can thiep khi chay qua CLI
    if (php_sapi_name() !== 'cli' && isset($_SERVER['HTTP_HOST'])) {
        // 1. Nhan dien giao thuc SSL/HTTPS (ho tro ca Reverse Proxy / Cloudflare)
        $is_https = (!empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off')
            || (isset($_SERVER['SERVER_PORT']) && (int)$_SERVER['SERVER_PORT'] === 443)
            || (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https')
            || (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && strtolower($_SERVER['HTTP_X_FORWARDED_SSL']) === 'on');

        $protocol = $is_https ? 'https://' : 'http://';
        $host = $_SERVER['HTTP_HOST'];

        // 2. Tinh toan duong dan thu muc con (subfolder) tu SCRIPT_NAME
        $raw_script = isset($_SERVER['SCRIPT_NAME']) ? $_SERVER['SCRIPT_NAME'] : '/index.php';
        $script_dir = str_replace('\\', '/', dirname($raw_script));
        
        // Loai bo cac thu muc he thong neu file dang chay nam trong wp-admin hoac wp-content
        $clean_dir = preg_replace('#/(wp-admin|wp-content|wp-includes).*$#', '', $script_dir);
        $clean_dir = trim($clean_dir, '/');
        $site_path = ($clean_dir === '' || $clean_dir === '.') ? '' : '/' . $clean_dir;

        // 3. Hop nhat thanh Base URL day du
        $dynamic_site_url = rtrim($protocol . $host . $site_path, '/');

        // 4. Khai bao hang so neu chua co
        if (!defined('WP_HOME')) {
            define('WP_HOME', $dynamic_site_url);
        }
        if (!defined('WP_SITEURL')) {
            define('WP_SITEURL', $dynamic_site_url);
        }
    }
}
