<?php
/**
 * Trình Cài Đặt WordPress 1-Click (1-Click WordPress Package Installer)
 * 
 * Tự động nhập Database, thiết lập wp-config.php, và thực thi Safe Serialized Search & Replace URL.
 * Tích hợp cơ chế bảo mật 5 lớp:
 *  1. Auth Token Verification
 *  2. Self-Locking / Anti-Replay Mechanism
 *  3. TTL Expiration (24 giờ)
 *  4. Safe Multi-tier Windows/Apache Self-Destruct Fallback
 *  5. Safe Serialized Data Replacement (Không làm hỏng layout Flatsome / WooCommerce)
 *
 * Generated by wordpress-packaging-handover skill
 */

// Ngăn chặn hiển thị lỗi ra màn hình làm lộ thông tin nhạy cảm, nhưng ghi log đầy đủ
@ini_set('display_errors', '0');
@error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
@set_time_limit(600);
@ini_set('memory_limit', '512M');

// ==============================================================================
// 1. CÁC HẰNG SỐ CẤU HÌNH & PLACEHOLDERS ĐƯỢC BUILDER TIÊM VÀO
// ==============================================================================
define('SETUP_AUTH_TOKEN', '{{AUTH_TOKEN}}');
define('SETUP_DEFAULT_DB', '{{DEFAULT_DB_NAME}}');
define('SETUP_SQL_FILE', '{{SQL_FILENAME}}');
define('SETUP_GENERATED_AT', '{{GENERATED_TIMESTAMP}}');

// ==============================================================================
// 2. CÁC HÀM TIỆN ÍCH AN TOÀN & BẢO MẬT
// ==============================================================================

/**
 * Lấy Auth Token từ request (GET hoặc POST)
 */
function get_request_token() {
    if (!empty($_POST['token'])) {
        return trim((string)$_POST['token']);
    }
    if (!empty($_GET['key'])) {
        return trim((string)$_GET['key']);
    }
    if (!empty($_GET['token'])) {
        return trim((string)$_GET['token']);
    }
    return '';
}

/**
 * Kiểm tra tính hợp lệ của Auth Token (sử dụng so sánh an toàn hash_equals)
 */
function is_token_valid($input_token) {
    if (empty($input_token)) {
        return false;
    }
    return hash_equals(SETUP_AUTH_TOKEN, $input_token);
}

/**
 * Kiểm tra thời hạn hoạt động của trình cài đặt (TTL 24 giờ)
 */
function check_ttl_expiration() {
    $created_time = is_numeric(SETUP_GENERATED_AT) ? (int)SETUP_GENERATED_AT : @filemtime(__FILE__);
    if (!$created_time || $created_time <= 0) {
        $created_time = time();
    }
    $ttl_limit = 86400; // 24 giờ tính bằng giây
    $elapsed = time() - $created_time;
    return [
        'expired' => $elapsed > $ttl_limit,
        'remaining_seconds' => max(0, $ttl_limit - $elapsed),
        'created_at' => $created_time
    ];
}

/**
 * Kiểm tra cơ chế tự khóa (Self-Locking): Nếu website đã cài đặt và DB đã có dữ liệu -> Khóa vĩnh viễn
 */
function check_self_locking() {
    $config_file = __DIR__ . '/wp-config.php';
    if (!file_exists($config_file)) {
        return false;
    }

    $config_content = @file_get_contents($config_file);
    if (!$config_content) {
        return false;
    }

    preg_match("/define\s*\(\s*['\"]DB_NAME['\"]\s*,\s*['\"](.*?)['\"]\s*\)/", $config_content, $m_name);
    preg_match("/define\s*\(\s*['\"]DB_USER['\"]\s*,\s*['\"](.*?)['\"]\s*\)/", $config_content, $m_user);
    preg_match("/define\s*\(\s*['\"]DB_PASSWORD['\"]\s*,\s*['\"](.*?)['\"]\s*\)/", $config_content, $m_pass);
    preg_match("/define\s*\(\s*['\"]DB_HOST['\"]\s*,\s*['\"](.*?)['\"]\s*\)/", $config_content, $m_host);
    preg_match("/\\\$table_prefix\s*=\s*['\"](.*?)['\"]/", $config_content, $m_prefix);

    $db_name = $m_name[1] ?? '';
    $db_user = $m_user[1] ?? '';
    $db_pass = $m_pass[1] ?? '';
    $db_host = $m_host[1] ?? 'localhost';
    $prefix  = $m_prefix[1] ?? 'wp_';

    if (empty($db_name) || empty($db_user)) {
        return false;
    }

    try {
        $pdo = new PDO("mysql:host={$db_host};dbname={$db_name};charset=utf8mb4", $db_user, $db_pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_SILENT,
            PDO::ATTR_TIMEOUT => 2
        ]);
        $stmt = $pdo->query("SELECT option_value FROM `{$prefix}options` WHERE option_name = 'siteurl' LIMIT 1");
        if ($stmt) {
            $siteurl = $stmt->fetchColumn();
            if (!empty($siteurl)) {
                return [
                    'locked' => true,
                    'siteurl' => $siteurl,
                    'dbname' => $db_name
                ];
            }
        }
    } catch (Throwable $e) {
        return false;
    }

    return false;
}

/**
 * Tự động phát hiện URL hiện tại của thư mục cài đặt
 */
function detect_current_url() {
    $is_https = (!empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off')
        || (isset($_SERVER['SERVER_PORT']) && (int)$_SERVER['SERVER_PORT'] === 443)
        || (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https')
        || (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && strtolower($_SERVER['HTTP_X_FORWARDED_SSL']) === 'on');

    $protocol = $is_https ? 'https://' : 'http://';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';

    $raw_script = $_SERVER['SCRIPT_NAME'] ?? '/setup.php';
    $script_dir = str_replace('\\', '/', dirname($raw_script));
    $clean_dir  = preg_replace('#/(wp-admin|wp-content|wp-includes).*$#', '', $script_dir);
    $clean_dir  = trim($clean_dir, '/');
    $site_path  = ($clean_dir === '' || $clean_dir === '.') ? '' : '/' . $clean_dir;

    return rtrim($protocol . $host . $site_path, '/');
}

/**
 * Tự hủy file setup.php an toàn với Fallback 3 tầng (Windows/Apache lock fallback)
 */
function perform_self_destruct() {
    $file = __FILE__;

    // Tầng 1: Thử xóa trực tiếp bằng unlink
    if (@unlink($file)) {
        return [
            'status' => 'success',
            'message' => 'Đã xóa file cài đặt setup.php thành công khỏi máy chủ!'
        ];
    }

    // Tầng 2: Ghi đè vô hiệu hóa và đổi tên (Fallback cho Windows do Apache giữ handle)
    $disabled_stub = "<?php\n/** Trình cài đặt đã bị vô hiệu hóa an toàn */\nhttp_response_code(404);\nexit('404 Not Found - Setup disabled.');\n";
    $overwritten = @file_put_contents($file, $disabled_stub) !== false;
    $renamed_path = $file . '.disabled.' . time();
    $renamed = @rename($file, $renamed_path);

    if ($renamed) {
        return [
            'status' => 'success',
            'message' => 'Đã vô hiệu hóa và đổi tên file setup.php thành ' . basename($renamed_path) . ' thành công!'
        ];
    }

    if ($overwritten) {
        return [
            'status' => 'warning',
            'message' => 'Nội dung file setup.php đã được ghi đè vô hiệu hóa an toàn. Vui lòng xóa file thủ công khi thuận tiện.'
        ];
    }

    // Tầng 3: Cảnh báo xóa tay bắt buộc
    return [
        'status' => 'danger',
        'message' => 'Máy chủ không cho phép tự động xóa hoặc ghi đè file. BẠN CẦN XÓA THỦ CÔNG FILE NÀY ĐỂ BẢO MẬT: ' . $file
    ];
}

/**
 * Kiểm tra xem chuỗi có phải dữ liệu PHP Serialized hay không
 */
function is_serialized_string_format($data) {
    if (!is_string($data)) {
        return false;
    }
    $data = trim($data);
    if ($data === 'N;') {
        return true;
    }
    if (strlen($data) < 4) {
        return false;
    }
    if ($data[1] !== ':') {
        return false;
    }
    $lastc = substr($data, -1);
    if ($lastc !== ';' && $lastc !== '}') {
        return false;
    }
    $token = $data[0];
    switch ($token) {
        case 's':
            if (substr($data, -2, 1) !== '"') {
                return false;
            }
        case 'a':
        case 'O':
        case 'b':
        case 'i':
        case 'd':
            return (bool)preg_match("/^{$token}:[0-9]+:/s", $data);
    }
    return false;
}

/**
 * Thuật toán Safe Serialized Search & Replace (Đếm độ dài byte UTF-8 chuẩn xác)
 * Đảm bảo các cấu hình serialized của Flatsome UX Builder, WooCommerce, ACF không bị hỏng layout.
 */
function safe_replace_serialized_bytes($data, $search, $replace) {
    if (empty($search) || $search === $replace || !is_string($data) || strpos($data, $search) === false) {
        return $data;
    }

    // Nếu không phải định dạng serialized, thay thế chuỗi thông thường
    if (!is_serialized_string_format($data)) {
        return str_replace($search, $replace, $data);
    }

    $len = strlen($data);
    $result = '';
    $i = 0;

    while ($i < $len) {
        // Nhận diện cú pháp bắt đầu của chuỗi serialized: s:<length>:"
        if ($data[$i] === 's' && $i + 1 < $len && $data[$i + 1] === ':') {
            $colon_pos = strpos($data, ':', $i + 2);
            if ($colon_pos !== false && $colon_pos + 1 < $len && $data[$colon_pos + 1] === '"') {
                $num_str = substr($data, $i + 2, $colon_pos - ($i + 2));
                if (ctype_digit($num_str)) {
                    $str_len = (int)$num_str;
                    $str_start = $colon_pos + 2;
                    // Kiểm tra chuỗi kết thúc đúng với ";
                    if ($str_start + $str_len <= $len && substr($data, $str_start + $str_len, 2) === '";') {
                        $str_content = substr($data, $str_start, $str_len);
                        if (strpos($str_content, $search) !== false) {
                            $replaced_content = str_replace($search, $replace, $str_content);
                            $new_len = strlen($replaced_content); // Tính độ dài theo byte (chuẩn PHP serialize)
                            $result .= 's:' . $new_len . ':"' . $replaced_content . '";';
                        } else {
                            $result .= 's:' . $str_len . ':"' . $str_content . '";';
                        }
                        $i = $str_start + $str_len + 2;
                        continue;
                    }
                }
            }
        }

        $result .= $data[$i];
        $i++;
    }

    return $result;
}

/**
 * Thực thi file SQL nạp dữ liệu theo phương pháp Streaming (chống tràn RAM)
 */
function execute_sql_file($pdo, $sql_filepath) {
    if (!file_exists($sql_filepath)) {
        throw new Exception("Không tìm thấy file SQL cơ sở dữ liệu tại: " . htmlspecialchars($sql_filepath));
    }

    $handle = @fopen($sql_filepath, 'r');
    if (!$handle) {
        throw new Exception("Không thể mở file SQL để đọc. Vui lòng kiểm tra quyền truy cập file!");
    }

    // Tắt các ràng buộc để tăng tốc và tránh lỗi khóa ngoại khi import
    $pdo->exec("SET FOREIGN_KEY_CHECKS = 0;");
    $pdo->exec("SET UNIQUE_CHECKS = 0;");
    $pdo->exec("SET AUTOCOMMIT = 0;");

    $query = '';
    $in_string = false;
    $string_char = '';
    $escaped = false;
    $executed_count = 0;

    while (($line = fgets($handle)) !== false) {
        $trimmed_line = trim($line);

        // Bỏ qua dòng chú thích khi không nằm trong chuỗi
        if (!$in_string) {
            if ($trimmed_line === '' || strpos($trimmed_line, '--') === 0 || strpos($trimmed_line, '#') === 0) {
                continue;
            }
            if (strpos($trimmed_line, '/*') === 0 && substr($trimmed_line, -2) === '*/' && strpos($trimmed_line, '/*!') !== 0) {
                continue;
            }
        }

        $len = strlen($line);
        for ($i = 0; $i < $len; $i++) {
            $char = $line[$i];

            if ($escaped) {
                $escaped = false;
                $query .= $char;
                continue;
            }

            if ($char === '\\') {
                $escaped = true;
                $query .= $char;
                continue;
            }

            if ($in_string) {
                if ($char === $string_char) {
                    $in_string = false;
                }
                $query .= $char;
            } else {
                if ($char === "'" || $char === '"' || $char === '`') {
                    $in_string = true;
                    $string_char = $char;
                    $query .= $char;
                } elseif ($char === ';') {
                    $stmt = trim($query);
                    if ($stmt !== '') {
                        $pdo->exec($stmt);
                        $executed_count++;
                    }
                    $query = '';
                } else {
                    $query .= $char;
                }
            }
        }
    }

    $stmt = trim($query);
    if ($stmt !== '') {
        $pdo->exec($stmt);
        $executed_count++;
    }

    fclose($handle);

    // Bật lại các ràng buộc và xác nhận giao dịch
    $pdo->exec("COMMIT;");
    $pdo->exec("SET FOREIGN_KEY_CHECKS = 1;");
    $pdo->exec("SET UNIQUE_CHECKS = 1;");
    $pdo->exec("SET AUTOCOMMIT = 1;");

    return $executed_count;
}

/**
 * Cập nhật file wp-config.php (hoặc tạo mới từ wp-config-sample.php)
 */
function update_or_create_wp_config($db_name, $db_user, $db_pass, $db_host) {
    $config_file = __DIR__ . '/wp-config.php';
    $sample_file = __DIR__ . '/wp-config-sample.php';

    $content = '';
    if (file_exists($config_file)) {
        $content = file_get_contents($config_file);
    } elseif (file_exists($sample_file)) {
        $content = file_get_contents($sample_file);
    } else {
        throw new Exception("Không tìm thấy file wp-config.php hoặc wp-config-sample.php trong thư mục gốc!");
    }

    // Cập nhật thông số kết nối Database
    $content = preg_replace("/(define\s*\(\s*['\"]DB_NAME['\"]\s*,\s*['\"])(.*?)(['\"]\s*\);)/", "\${1}{$db_name}\${3}", $content);
    $content = preg_replace("/(define\s*\(\s*['\"]DB_USER['\"]\s*,\s*['\"])(.*?)(['\"]\s*\);)/", "\${1}{$db_user}\${3}", $content);
    $content = preg_replace("/(define\s*\(\s*['\"]DB_PASSWORD['\"]\s*,\s*['\"])(.*?)(['\"]\s*\);)/", "\${1}{$db_pass}\${3}", $content);
    $content = preg_replace("/(define\s*\(\s*['\"]DB_HOST['\"]\s*,\s*['\"])(.*?)(['\"]\s*\);)/", "\${1}{$db_host}\${3}", $content);

    // Chèn khối mã Dynamic URL nếu chưa có
    if (strpos($content, 'WP_HOME') === false && strpos($content, 'DYNAMIC_WP_URL') === false) {
        $dynamic_snippet = "\n// DYNAMIC_WP_URL: Tu dong nhan dien URL cho Localhost / Live Server\n"
            . "if (!defined('WP_HOME') || !defined('WP_SITEURL')) {\n"
            . "    if (php_sapi_name() !== 'cli' && isset(\$_SERVER['HTTP_HOST'])) {\n"
            . "        \$is_ssl = (!empty(\$_SERVER['HTTPS']) && strtolower(\$_SERVER['HTTPS']) !== 'off') || (isset(\$_SERVER['SERVER_PORT']) && (int)\$_SERVER['SERVER_PORT'] === 443);\n"
            . "        \$proto  = \$is_ssl ? 'https://' : 'http://';\n"
            . "        \$s_dir  = str_replace('\\\\', '/', dirname(\$_SERVER['SCRIPT_NAME'] ?? '/index.php'));\n"
            . "        \$clean  = trim(preg_replace('#/(wp-admin|wp-content|wp-includes).*$#', '', \$s_dir), '/');\n"
            . "        \$b_url  = rtrim(\$proto . \$_SERVER['HTTP_HOST'] . (\$clean === '' ? '' : '/' . \$clean), '/');\n"
            . "        if (!defined('WP_HOME')) define('WP_HOME', \$b_url);\n"
            . "        if (!defined('WP_SITEURL')) define('WP_SITEURL', \$b_url);\n"
            . "    }\n"
            . "}\n\n";

        if (strpos($content, "/* That's all, stop editing!") !== false) {
            $content = str_replace("/* That's all, stop editing!", $dynamic_snippet . "/* That's all, stop editing!", $content);
        } else {
            $content .= $dynamic_snippet;
        }
    }

    if (@file_put_contents($config_file, $content) === false) {
        throw new Exception("Không thể ghi file wp-config.php. Vui lòng cấp quyền ghi (Write Permission) cho thư mục website!");
    }
}

/**
 * Thực thi Search & Replace an toàn trên toàn bộ cơ sở dữ liệu
 */
function perform_database_search_replace($pdo, $prefix, $old_url, $new_url) {
    if (empty($old_url) || empty($new_url) || $old_url === $new_url) {
        return 0;
    }

    $affected_count = 0;

    // 1. Bảng Options
    $stmt = $pdo->prepare("SELECT option_id, option_value FROM `{$prefix}options` WHERE option_value LIKE :search");
    $stmt->execute([':search' => '%' . $old_url . '%']);
    $update_stmt = $pdo->prepare("UPDATE `{$prefix}options` SET option_value = :new_val WHERE option_id = :id");

    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        $new_val = safe_replace_serialized_bytes($row['option_value'], $old_url, $new_url);
        if ($new_val !== $row['option_value']) {
            $update_stmt->execute([':new_val' => $new_val, ':id' => $row['option_id']]);
            $affected_count++;
        }
    }

    // 2. Bảng Postmeta
    $stmt = $pdo->prepare("SELECT meta_id, meta_value FROM `{$prefix}postmeta` WHERE meta_value LIKE :search");
    $stmt->execute([':search' => '%' . $old_url . '%']);
    $update_stmt = $pdo->prepare("UPDATE `{$prefix}postmeta` SET meta_value = :new_val WHERE meta_id = :id");

    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        $new_val = safe_replace_serialized_bytes($row['meta_value'], $old_url, $new_url);
        if ($new_val !== $row['meta_value']) {
            $update_stmt->execute([':new_val' => $new_val, ':id' => $row['meta_id']]);
            $affected_count++;
        }
    }

    // 3. Bảng Posts
    $stmt = $pdo->prepare("SELECT ID, post_content, guid FROM `{$prefix}posts` WHERE post_content LIKE :search OR guid LIKE :search");
    $stmt->execute([':search' => '%' . $old_url . '%']);
    $update_stmt = $pdo->prepare("UPDATE `{$prefix}posts` SET post_content = :content, guid = :guid WHERE ID = :id");

    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        $new_content = safe_replace_serialized_bytes($row['post_content'], $old_url, $new_url);
        $new_guid = safe_replace_serialized_bytes($row['guid'], $old_url, $new_url);
        if ($new_content !== $row['post_content'] || $new_guid !== $row['guid']) {
            $update_stmt->execute([':content' => $new_content, ':guid' => $new_guid, ':id' => $row['ID']]);
            $affected_count++;
        }
    }

    return $affected_count;
}

// ==============================================================================
// 3. XỬ LÝ GIAO DIỆN CHUẨN HTML & CSS HIỆN ĐẠI
// ==============================================================================
function render_html_layout($title, $body_content, $badge = '') {
    ?>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($title); ?> - WordPress 1-Click Installer</title>
    <style>
        :root {
            --primary: #2563eb;
            --primary-hover: #1d4ed8;
            --bg: #f8fafc;
            --card-bg: #ffffff;
            --text-main: #0f172a;
            --text-muted: #64748b;
            --border: #e2e8f0;
            --success-bg: #f0fdf4;
            --success-text: #166534;
            --success-border: #bbf7d0;
            --danger-bg: #fef2f2;
            --danger-text: #991b1b;
            --danger-border: #fecaca;
            --warning-bg: #fffbeb;
            --warning-text: #92400e;
            --warning-border: #fde68a;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg);
            color: var(--text-main);
            line-height: 1.5;
            padding: 40px 16px;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .container {
            width: 100%;
            max-width: 680px;
            background: var(--card-bg);
            border-radius: 16px;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.08), 0 8px 10px -6px rgba(0, 0, 0, 0.04);
            border: 1px solid var(--border);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
            padding: 32px 36px;
            color: #ffffff;
            position: relative;
        }
        .header h1 {
            font-size: 22px;
            font-weight: 700;
            letter-spacing: -0.02em;
            margin-bottom: 6px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .header p {
            font-size: 13.5px;
            color: #94a3b8;
        }
        .badge {
            display: inline-block;
            font-size: 11px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            padding: 3px 10px;
            border-radius: 9999px;
            background: rgba(255, 255, 255, 0.15);
            color: #38bdf8;
            margin-top: 10px;
        }
        .content {
            padding: 32px 36px;
        }
        .alert {
            padding: 14px 18px;
            border-radius: 10px;
            margin-bottom: 24px;
            font-size: 14px;
            line-height: 1.6;
            border: 1px solid transparent;
        }
        .alert-success { background: var(--success-bg); color: var(--success-text); border-color: var(--success-border); }
        .alert-danger { background: var(--danger-bg); color: var(--danger-text); border-color: var(--danger-border); }
        .alert-warning { background: var(--warning-bg); color: var(--warning-text); border-color: var(--warning-border); }
        .alert-info { background: #eff6ff; color: #1e40af; border-color: #bfdbfe; }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            display: block;
            font-size: 13.5px;
            font-weight: 600;
            margin-bottom: 6px;
            color: var(--text-main);
        }
        .form-group .hint {
            font-size: 12px;
            color: var(--text-muted);
            margin-top: 4px;
        }
        .form-control {
            width: 100%;
            padding: 10px 14px;
            font-size: 14px;
            border: 1px solid var(--border);
            border-radius: 8px;
            outline: none;
            transition: border-color 0.2s, box-shadow 0.2s;
            background-color: #ffffff;
            color: var(--text-main);
        }
        .form-control:focus {
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.15);
        }
        .grid-2 {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 16px;
        }
        .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            padding: 12px 20px;
            font-size: 14px;
            font-weight: 600;
            border-radius: 8px;
            cursor: pointer;
            text-decoration: none;
            transition: all 0.2s;
            border: none;
            width: 100%;
        }
        .btn-primary {
            background-color: var(--primary);
            color: #ffffff;
        }
        .btn-primary:hover {
            background-color: var(--primary-hover);
        }
        .btn-danger {
            background-color: #dc2626;
            color: #ffffff;
        }
        .btn-danger:hover {
            background-color: #b91c1c;
        }
        .btn-secondary {
            background-color: #e2e8f0;
            color: #334155;
        }
        .btn-secondary:hover {
            background-color: #cbd5e1;
        }
        .card-box {
            background: #f8fafc;
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 18px;
            margin-bottom: 24px;
        }
        .card-box-title {
            font-size: 13px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-muted);
            margin-bottom: 12px;
        }
        .creds-row {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px dashed var(--border);
            font-size: 14px;
        }
        .creds-row:last-child { border-bottom: none; }
        .creds-label { color: var(--text-muted); }
        .creds-value { font-weight: 600; font-family: monospace; font-size: 14px; }
        .footer-note {
            text-align: center;
            font-size: 12px;
            color: var(--text-muted);
            margin-top: 24px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83"/></svg>
            <?php echo htmlspecialchars($title); ?>
        </h1>
        <p>Bộ công cụ cài đặt & khôi phục toàn diện WordPress (Bản giao độc lập)</p>
        <?php if (!empty($badge)): ?>
            <div class="badge"><?php echo htmlspecialchars($badge); ?></div>
        <?php endif; ?>
    </div>
    <div class="content">
        <?php echo $body_content; ?>
    </div>
</div>
</body>
</html>
    <?php
}

// ==============================================================================
// 4. LUỒNG ĐIỀU PHỐI VÀ XỬ LÝ CHÍNH
// ==============================================================================

if (defined('SETUP_TESTING_MODE') && SETUP_TESTING_MODE === true) {
    return;
}

$request_token = get_request_token();
$action = $_GET['action'] ?? $_POST['action'] ?? '';

// Xử lý tự hủy file nếu có yêu cầu
if ($action === 'self_destruct') {
    // Chỉ cho phép tự hủy nếu có token hợp lệ hoặc trang đã bị khóa
    $lock_info = check_self_locking();
    if (!is_token_valid($request_token) && !$lock_info) {
        http_response_code(403);
        $html = '<div class="alert alert-danger"><strong>403 Forbidden:</strong> Yêu cầu Khóa xác thực (Auth Token) hợp lệ để thực hiện thao tác tự hủy.</div>';
        render_html_layout('Từ Chối Truy Cập', $html, 'Lỗi Bảo Mật');
        exit;
    }

    $destruct_result = perform_self_destruct();
    $alert_class = 'alert-' . ($destruct_result['status'] === 'success' ? 'success' : ($destruct_result['status'] === 'warning' ? 'warning' : 'danger'));

    $html = '<div class="alert ' . $alert_class . '"><strong>' . htmlspecialchars($destruct_result['message']) . '</strong></div>';
    $html .= '<p style="margin-bottom: 20px; font-size: 14px; color: var(--text-muted);">Trình cài đặt setup.php đã được xử lý an toàn nhằm loại bỏ hoàn toàn các rủi ro bảo mật cho website của bạn.</p>';
    $html .= '<a href="' . htmlspecialchars(detect_current_url()) . '/wp-admin/" class="btn btn-primary">Đăng Nhập Quản Trị WP-Admin</a>';

    render_html_layout('Tự Hủy Trình Cài Đặt', $html, 'Bảo Mật Hệ Thống');
    exit;
}

// --- LAYER 1: KIỂM TRA AUTH TOKEN ---
if (!is_token_valid($request_token)) {
    http_response_code(403);
    $error_msg = !empty($request_token) ? 'Khóa xác thực (Auth Token) không chính xác. Vui lòng kiểm tra lại!' : '';

    $html = '';
    if (!empty($error_msg)) {
        $html .= '<div class="alert alert-danger"><strong>403 Forbidden:</strong> ' . htmlspecialchars($error_msg) . '</div>';
    } else {
        $html .= '<div class="alert alert-info"><strong>Yêu Cầu Xác Thực:</strong> Để bảo vệ an toàn cho website, trình cài đặt yêu cầu <strong>Khóa xác thực (Auth Token)</strong> được cấp trong báo cáo đóng gói dự án.</div>';
    }

    $html .= '<form method="GET" action="">';
    $html .= '  <div class="form-group">';
    $html .= '    <label for="input_key">Nhập Auth Token</label>';
    $html .= '    <input type="text" id="input_key" name="key" class="form-control" placeholder="Ví dụ: a1b2c3d4e5f6..." required autofocus>';
    $html .= '    <div class="hint">Khóa này được sinh tự động khi chạy lệnh đóng gói dự án.</div>';
    $html .= '  </div>';
    $html .= '  <button type="submit" class="btn btn-primary">Xác Thực & Mở Khóa Trình Cài Đặt</button>';
    $html .= '</form>';

    render_html_layout('Xác Thực Quyền Truy Cập', $html, 'Cơ Chế Bảo Mật Lớp 1');
    exit;
}

// --- LAYER 2: KIỂM TRA THỜI GIAN HOẠT ĐỘNG (TTL 24H) ---
$ttl_info = check_ttl_expiration();
if ($ttl_info['expired']) {
    http_response_code(403);
    $html = '<div class="alert alert-danger"><strong>Khóa Cài Đặt Đã Hết Hạn:</strong> File setup.php này đã vượt quá thời hạn sử dụng an toàn (24 giờ kể từ thời điểm tạo). Trình cài đặt đã tự động khóa vĩnh viễn để bảo vệ máy chủ.</div>';
    $html .= '<p style="margin-bottom: 24px; font-size: 14px; color: var(--text-muted);">Vui lòng thực hiện lại quy trình đóng gói dự án để sinh mã token mới, hoặc xóa file này ngay lập tức.</p>';
    $html .= '<a href="?action=self_destruct&token=' . urlencode($request_token) . '" class="btn btn-danger" onclick="return confirm(\'Bạn có chắc chắn muốn xóa file này không?\');">Xóa Ngay File setup.php Này</a>';

    render_html_layout('Trình Cài Đặt Đã Hết Hạn', $html, 'Cơ Chế Bảo Mật Lớp 2 (TTL)');
    exit;
}

// --- LAYER 3: KIỂM TRA TỰ KHÓA (SELF-LOCKING / ANTI-REPLAY) ---
$lock_status = check_self_locking();
if ($lock_status && $lock_status['locked']) {
    http_response_code(403);
    $html = '<div class="alert alert-warning"><strong>Website Đã Được Cài Đặt:</strong> Cơ sở dữ liệu <code>' . htmlspecialchars($lock_status['dbname']) . '</code> đã được kết nối và cấu hình hoàn tất cho tên miền <code>' . htmlspecialchars($lock_status['siteurl']) . '</code>.</div>';
    $html .= '<p style="margin-bottom: 20px; font-size: 14px; color: var(--text-muted);">Trình cài đặt <code>setup.php</code> đã tự động kích hoạt tính năng Tự Khóa (Self-Locking) để ngăn chặn các cuộc tấn công ghi đè hoặc nạp lại dữ liệu (Anti-Replay Attack).</p>';
    $html .= '<div style="display: flex; gap: 12px; margin-bottom: 16px;">';
    $html .= '  <a href="' . htmlspecialchars($lock_status['siteurl']) . '" class="btn btn-secondary" target="_blank">Xem Trang Chủ</a>';
    $html .= '  <a href="' . htmlspecialchars($lock_status['siteurl']) . '/wp-admin/" class="btn btn-primary" target="_blank">Vào Quản Trị WP-Admin</a>';
    $html .= '</div>';
    $html .= '<a href="?action=self_destruct&token=' . urlencode($request_token) . '" class="btn btn-danger" onclick="return confirm(\'Bạn có chắc chắn muốn xóa file setup.php này để bảo vệ website?\');">Tự Hủy File setup.php Ngay (Khuyến Nghị)</a>';

    render_html_layout('Trình Cài Đặt Đã Tự Động Khóa', $html, 'Cơ Chế Bảo Mật Lớp 3 (Self-Locking)');
    exit;
}

// --- XỬ LÝ THỰC THI CÀI ĐẶT (KHI SUBMIT FORM) ---
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($action === 'do_install')) {
    $db_host = trim($_POST['db_host'] ?? 'localhost');
    $db_name = trim($_POST['db_name'] ?? '');
    $db_user = trim($_POST['db_user'] ?? 'root');
    $db_pass = trim($_POST['db_pass'] ?? '');
    $site_url = rtrim(trim($_POST['site_url'] ?? detect_current_url()), '/');
    $sql_filename = trim($_POST['sql_file'] ?? SETUP_SQL_FILE);

    $errors = [];
    if (empty($db_name)) {
        $errors[] = 'Vui lòng nhập tên Database!';
    }
    if (empty($db_user)) {
        $errors[] = 'Vui lòng nhập tên người dùng Database!';
    }

    $sql_path = __DIR__ . '/' . $sql_filename;
    if (!file_exists($sql_path)) {
        // Thử tìm file sql bất kỳ trong thư mục
        $glob_sqls = glob(__DIR__ . '/*.sql');
        if (!empty($glob_sqls)) {
            $sql_path = $glob_sqls[0];
            $sql_filename = basename($sql_path);
        } else {
            $errors[] = 'Không tìm thấy file SQL cơ sở dữ liệu: ' . htmlspecialchars($sql_filename);
        }
    }

    if (empty($errors)) {
        try {
            // 1. Kết nối MySQL Server và tạo Database nếu chưa có
            $pdo_init = new PDO("mysql:host={$db_host};charset=utf8mb4", $db_user, $db_pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_TIMEOUT => 5
            ]);
            $pdo_init->exec("CREATE DATABASE IF NOT EXISTS `{$db_name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            unset($pdo_init);

            // 2. Kết nối trực tiếp vào Database đã chọn
            $pdo = new PDO("mysql:host={$db_host};dbname={$db_name};charset=utf8mb4", $db_user, $db_pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);

            // 3. Thực thi nạp file SQL
            $executed_queries = execute_sql_file($pdo, $sql_path);

            // 4. Nhận diện prefix bảng WordPress
            $tables_stmt = $pdo->query("SHOW TABLES LIKE '%options'");
            $tables = $tables_stmt->fetchAll(PDO::FETCH_COLUMN);
            $prefix = 'wp_';
            if (!empty($tables)) {
                if (preg_match('/^(.*?)options$/', $tables[0], $pm)) {
                    $prefix = $pm[1];
                }
            }

            // 5. Lấy URL cũ từ cơ sở dữ liệu vừa import
            $old_url_stmt = $pdo->query("SELECT option_value FROM `{$prefix}options` WHERE option_name = 'siteurl' LIMIT 1");
            $old_url = $old_url_stmt ? rtrim((string)$old_url_stmt->fetchColumn(), '/') : '';

            // 6. Thực thi Safe Serialized Search & Replace
            $replaced_rows = 0;
            if (!empty($old_url) && $old_url !== $site_url) {
                $replaced_rows = perform_database_search_replace($pdo, $prefix, $old_url, $site_url);
            }

            // 7. Cập nhật wp-config.php
            update_or_create_wp_config($db_name, $db_user, $db_pass, $db_host);

            // 8. Hiển thị màn hình thành công
            $html = '<div class="alert alert-success"><strong>Cài đặt hoàn tất thành công!</strong> Website của bạn đã sẵn sàng hoạt động ngay lập tức.</div>';
            
            $html .= '<div class="card-box">';
            $html .= '  <div class="card-box-title">Thống Kê Khôi Phục Hệ Thống</div>';
            $html .= '  <div class="creds-row"><span class="creds-label">Cơ sở dữ liệu:</span><span class="creds-value">' . htmlspecialchars($db_name) . '</span></div>';
            $html .= '  <div class="creds-row"><span class="creds-label">Câu lệnh SQL đã nạp:</span><span class="creds-value">' . number_format($executed_queries) . ' truy vấn</span></div>';
            $html .= '  <div class="creds-row"><span class="creds-label">URL Cũ -> Mới:</span><span class="creds-value">' . htmlspecialchars($old_url ?: 'N/A') . ' &rarr; ' . htmlspecialchars($site_url) . '</span></div>';
            $html .= '  <div class="creds-row"><span class="creds-label">Dữ liệu Serialized cập nhật:</span><span class="creds-value">' . number_format($replaced_rows) . ' bản ghi an toàn</span></div>';
            $html .= '</div>';

            $html .= '<div class="card-box" style="border-left: 4px solid var(--primary);">';
            $html .= '  <div class="card-box-title">Thông Tin Quản Trị Mặc Định</div>';
            $html .= '  <div class="creds-row"><span class="creds-label">Tài khoản Admin:</span><span class="creds-value">admin</span></div>';
            $html .= '  <div class="creds-row"><span class="creds-label">Mật khẩu:</span><span class="creds-value">adminpassword123</span></div>';
            $html .= '  <div class="creds-row"><span class="creds-label">Trang Quản Trị:</span><span class="creds-value"><a href="' . htmlspecialchars($site_url) . '/wp-admin/" target="_blank">' . htmlspecialchars($site_url) . '/wp-admin/</a></span></div>';
            $html .= '</div>';

            $html .= '<div style="margin-bottom: 24px;">';
            $html .= '  <a href="?action=self_destruct&token=' . urlencode($request_token) . '" class="btn btn-danger" onclick="return confirm(\'Hành động này sẽ xóa file setup.php để ngăn người khác cài đặt lại. Bạn có chắc chắn?\');">';
            $html .= '    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>';
            $html .= '    TỰ HỦY FILE SETUP.PHP NGAY BÂY GIỜ (Khuyến Nghị Bắt Buộc)';
            $html .= '  </a>';
            $html .= '</div>';

            $html .= '<div style="display: flex; gap: 12px;">';
            $html .= '  <a href="' . htmlspecialchars($site_url) . '" class="btn btn-secondary" target="_blank">Xem Website</a>';
            $html .= '  <a href="' . htmlspecialchars($site_url) . '/wp-admin/" class="btn btn-primary" target="_blank">Đăng Nhập WP-Admin</a>';
            $html .= '</div>';

            render_html_layout('Cài Đặt Thành Công', $html, 'Khôi Phục Hoàn Tất');
            exit;

        } catch (Throwable $e) {
            $errors[] = 'Lỗi thực thi MySQL: ' . $e->getMessage();
        }
    }

    if (!empty($errors)) {
        $error_html = '<div class="alert alert-danger"><strong>Đã xảy ra lỗi:</strong><ul style="margin-left: 20px; margin-top: 6px;">';
        foreach ($errors as $err) {
            $error_html .= '<li>' . htmlspecialchars($err) . '</li>';
        }
        $error_html .= '</ul></div>';
    }
}

// --- HIỂN THỊ FORM CẤU HÌNH THÔNG SỐ CÀI ĐẶT ---
$detected_url = detect_current_url();
$default_db_name = SETUP_DEFAULT_DB !== '' ? SETUP_DEFAULT_DB : 'wordpress';
$default_sql_file = SETUP_SQL_FILE !== '' ? SETUP_SQL_FILE : 'database.sql';

$html = '';
if (!empty($error_html)) {
    $html .= $error_html;
} else {
    $html .= '<div class="alert alert-info">Hệ thống đã tự động nhận diện môi trường máy chủ. Vui lòng kiểm tra lại thông tin Database và bấm <strong>Tiến Hành Cài Đặt</strong>.</div>';
}

$html .= '<form method="POST" action="">';
$html .= '  <input type="hidden" name="action" value="do_install">';
$html .= '  <input type="hidden" name="token" value="' . htmlspecialchars($request_token) . '">';

$html .= '  <div class="grid-2">';
$html .= '    <div class="form-group">';
$html .= '      <label for="db_host">Database Host</label>';
$html .= '      <input type="text" id="db_host" name="db_host" class="form-control" value="localhost" required>';
$html .= '      <div class="hint">Thường là localhost hoặc 127.0.0.1</div>';
$html .= '    </div>';
$html .= '    <div class="form-group">';
$html .= '      <label for="db_name">Tên Database</label>';
$html .= '      <input type="text" id="db_name" name="db_name" class="form-control" value="' . htmlspecialchars($default_db_name) . '" required>';
$html .= '      <div class="hint">Tự động tạo mới nếu chưa tồn tại</div>';
$html .= '    </div>';
$html .= '  </div>';

$html .= '  <div class="grid-2">';
$html .= '    <div class="form-group">';
$html .= '      <label for="db_user">Tài khoản Database User</label>';
$html .= '      <input type="text" id="db_user" name="db_user" class="form-control" value="root" required>';
$html .= '      <div class="hint">Mặc định XAMPP/Laragon là root</div>';
$html .= '    </div>';
$html .= '    <div class="form-group">';
$html .= '      <label for="db_pass">Mật khẩu Database Password</label>';
$html .= '      <input type="password" id="db_pass" name="db_pass" class="form-control" value="" placeholder="(Trống trên localhost)">';
$html .= '      <div class="hint">Để trống nếu không có mật khẩu</div>';
$html .= '    </div>';
$html .= '  </div>';

$html .= '  <div class="form-group">';
$html .= '    <label for="site_url">URL Website (Tự động nhận diện)</label>';
$html .= '    <input type="text" id="site_url" name="site_url" class="form-control" value="' . htmlspecialchars($detected_url) . '" required>';
$html .= '    <div class="hint">Tất cả URL serialized cũ trong Flatsome/WooCommerce sẽ được thay thế an toàn sang URL này.</div>';
$html .= '  </div>';

$html .= '  <div class="form-group">';
$html .= '    <label for="sql_file">File SQL Dữ Liệu</label>';
$html .= '    <input type="text" id="sql_file" name="sql_file" class="form-control" value="' . htmlspecialchars($default_sql_file) . '" required>';
$html .= '    <div class="hint">Tệp tin SQL đi kèm gói cài đặt trong cùng thư mục.</div>';
$html .= '  </div>';

$html .= '  <button type="submit" class="btn btn-primary" style="margin-top: 10px;">';
$html .= '    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>';
$html .= '    Tiến Hành Cài Đặt & Cấu Hình Ngay';
$html .= '  </button>';
$html .= '</form>';

$html .= '<div class="footer-note">';
$html .= '  Trình cài đặt được bảo vệ bởi Khóa xác thực Token & Cơ chế Tự Hủy an toàn. Thời hạn: 24 giờ.';
$html .= '</div>';

render_html_layout('Thiết Lập Cài Đặt Website', $html, 'Sẵn Sàng Cài Đặt');
